//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::quote_price::Entity as QuotePrice;
pub use super::quote_sub::Entity as QuoteSub;
pub use super::quote_trade::Entity as QuoteTrade;
