//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "quote_trade")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub symbol: String,
    pub sequence: i64,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))", nullable)]
    pub price: Option<Decimal>,
    pub volume: Option<i32>,
    pub timestamp: i64,
    pub trade_type: Option<String>,
    pub direction: Option<i32>,
    pub trade_session: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
