//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "quote_price")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub symbol: String,
    pub sequence: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))", nullable)]
    pub last_done: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))", nullable)]
    pub open: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))", nullable)]
    pub high: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))", nullable)]
    pub low: Option<Decimal>,
    pub timestamp: i64,
    pub volume: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))", nullable)]
    pub turnover: Option<Decimal>,
    pub trade_status: Option<i32>,
    pub trade_session: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
